// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBubZOpJ4IKlw6f9G0amRveLcpU1lIXMhA',
    appId: '1:193321625646:web:f9c969b3126d759a88d7bf',
    messagingSenderId: '193321625646',
    projectId: 'mytro-c1eb1',
    authDomain: 'mytro-c1eb1.firebaseapp.com',
    storageBucket: 'mytro-c1eb1.appspot.com',
    measurementId: 'G-66PNCE9HEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwJYDUIsXt_Fspm2FNoz0q-JixJ6g-IaE',
    appId: '1:193321625646:android:6732842a8eedee0188d7bf',
    messagingSenderId: '193321625646',
    projectId: 'mytro-c1eb1',
    storageBucket: 'mytro-c1eb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO5pWAHpnC7-lOXHqX8MzIsQGigJhyOb0',
    appId: '1:193321625646:ios:9ed9ab540418dc5788d7bf',
    messagingSenderId: '193321625646',
    projectId: 'mytro-c1eb1',
    storageBucket: 'mytro-c1eb1.appspot.com',
    iosBundleId: 'com.example.figma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO5pWAHpnC7-lOXHqX8MzIsQGigJhyOb0',
    appId: '1:193321625646:ios:453078ff5d0f832388d7bf',
    messagingSenderId: '193321625646',
    projectId: 'mytro-c1eb1',
    storageBucket: 'mytro-c1eb1.appspot.com',
    iosBundleId: 'com.example.figma.RunnerTests',
  );
}
